### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/rintrinio#23]
- Excellent work, functions are clear and well documented.
- Your CONTRIBUTING mentions Poetry.
- Is the figure in `man` necessary?

**Comment by slbsolomon** [comment]
Removed man
@sirine-chahma can you please remove the poetry mention?

**Comment by aakanksha023** [comment]
- Addressed in commit 
https://github.com/UBC-MDS/rintrinio/pull/58/commits/87b7020d305584952224e32a1cc283884155f32b
