### ISSUE TITLE
Milestone 2 Feeback.

### ISSUE THREAD

**Issue by yavyx** [UBC-MDS/rintrinio#55]
- Excellent work with documentation and implementation.
- 8 tests failed, plus 2 warnings.

**Comment by slbsolomon** [comment]
As discussed over slack, 6 of the failures were related to a limitation of the free API: https://docs.intrinio.com/documentation/api_v2/limits

We added protection against this in Milestone 3

**Comment by slbsolomon** [comment]
All addressed in Milestone 3 - feel free to re-open if necessary.
