### ISSUE TITLE
Notes for submission - Everyone

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/rintrinio#9]

**Comment by Zhang-Haipeng** [comment]
○ Include the URL of your public project's repo in the README.md file of your milestone1's repo so that we know where to find it.
○ Create a release on your project repo named v0.1.0 and submit that URL in your milestone1 repo's README.md file so we know where to find it.
○ Use proper grammar and full sentences throughout the project, especially in your README.

**Comment by slbsolomon** [comment]
https://github.com/UBC-MDS/rintrinio/tree/v0.1.0
